version: '3.8'

services:
  fmp-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:80"
      - "7443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
    volumes:
      - ${APPDATA:-~/.microsoft/usersecrets}:/root/.microsoft/usersecrets:ro
      - ${APPDATA:-~/.aspnet/https}:/root/.aspnet/https:ro