version: '3.8'

services:
  ui:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - feature-management-network

  api:
    image: brian-swan/fmp_prototype_3:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - feature-management-network

networks:
  feature-management-network:
    driver: bridge